import { AuthProvider } from '@descope/nextjs-sdk';

import Navbar from "@/components/Navbar";
import "./globals.css";
import Footer from "@/components/Footer";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<AuthProvider projectId="P2vG4p7UDlLQapKxW9Qc1n8oDs7u">

		<html lang="en">
			<body>
				<Navbar />
				{children}
				<Footer />
			</body>
		</html>
		</AuthProvider>

	);
}
